version: 2.1
executors:
  juce-docker-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/raffasansone/TriumvirateBass/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
          
jobs:
  macos-build:
    macos:
      #xcode: 13.4.1
      xcode: 14.2.0
      #xcode: 13.0.0

    steps:
      - checkout
      
      - run: 
            name: Sync and Update Submodules
            command: 
                git submodule sync --recursive 
                && git submodule update --init --recursive
                && ls ff_meters
                && ls JUCE
                
      - run: 
            name: XCode Build 
            command: xcodebuild -project Builds/MacOSX/TriumvirateBass.xcodeproj -alltargets -parallelizeTargets -configuration Release build
      
      - run:
            name: List Build Directories
            command: ls -R /Users/distiller/project/Builds/MacOSX/
                && ls -R /Users/distiller/Library/Audio/Plug-Ins/
      
      - run:
            name: Package Artifacts
            command: tar -cvzf TriumvirateBass_Standalone.tar /Users/distiller/project/Builds/MacOSX/build/Release/TriumvirateBass.app
                && tar -cvzf TriumvirateBass_VST3.tar /Users/distiller/Library/Audio/Plug-Ins/VST3/TriumvirateBass.vst3
                && tar -cvzf TriumvirateBass_AU.tar /Users/distiller/Library/Audio/Plug-Ins/Components/TriumvirateBass.component
      
      - store_artifacts: 
            path: TriumvirateBass_Standalone.tar
            destination: TriumvirateBass_Standalone
      
      - store_artifacts:
            path: TriumvirateBass_VST3.tar
            destination: TriumvirateBass_VST3

      - store_artifacts:
            path: TriumvirateBass_AU.tar
            destination: TriumvirateBass_AU
          
workflows:
  juce-build-workflow:
    jobs:
      - macos-build:
          filters:
            branches:
              only:
                - circleci-project-setup
