version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/raffasansone/TriumvirateBass/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  macos-build:
    macos:
      xcode: 13.4.1
       
    steps:
      - checkout
      - run: xcodebuild -version

workflows:
  my-custom-workflow:
    jobs:
      - macos-build